name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for the frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust the Node.js version as needed

      # Install dependencies for frontend
      - name: Install frontend dependencies
        working-directory: ./frontend/myapp  # Adjust the directory if needed
        run: |
          npm install
          npm create vite@latest

      # Set up Node.js for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust the Node.js version for backend if needed

      # Install dependencies for backend
      - name: Install backend dependencies
        working-directory: ./backend  # Adjust the directory if needed
        run: npm install

      # Optionally run tests for frontend and backend
      - name: Run frontend tests
        working-directory: ./frontend/myapp  # Adjust the directory if needed
        run: npm test

      - name: Run backend tests
        working-directory: ./backend  # Adjust the directory if needed
        run: npm test
