name: Fullstack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # List files for debugging
    - name: List files in root
      run: ls -la

    # Setup Node.js for Frontend
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./frontend/myapp
      run: npm install

    # Run Frontend Tests
    - name: Run Frontend Tests
      working-directory: ./frontend/myapp
      run: npm test
      env:
        CI: true

    # Setup Node.js for Backend
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    # Run Backend Tests
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      env:
        CI: true
